---
- name: set workdir
  set_fact:
    workdir: "{{ gopath }}/src/github.com/openshift/installer"

- name: ensure that .kube dir exists
  file:
    path: /root/.kube
    state: directory

- name: copy the kubeconfig
  copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: /root/.kube/config
    remote_src: true
